create table if not exists public.china_jobs (
    id bigint generated by default as identity primary key,
    company_name text,
    ats_type text not null,
    ats_token text not null,
    ats_board_token text,
    ats_job_id text not null,
    title text,
    location_raw text,
    location_normalized text,
    is_china boolean not null default true,
    is_europe boolean not null default false,
    is_remote boolean not null default false,
    recency_status text,
    fetch_status text,
    ats_published_at text,
    ats_updated_at text,
    ats_date_normalized date,
    ats_date_source text,
    ats_age_days integer,
    ats_age_bucket text,
    first_seen_at text,
    last_seen_at text,
    fetched_at text,
    matched_location_keywords text,
    normalized_url text,
    url text,
    jd_text_length integer,
    jd_text text,
    imported_at timestamptz not null default now(),
    unique (ats_type, ats_token, ats_job_id)
);

create table if not exists public.china_companies (
    id bigint generated by default as identity primary key,
    company_name_guess text,
    ats_type text not null,
    ats_token text not null,
    api_status text,
    api_error text,
    total_open_jobs integer,
    china_keyword_hits integer,
    recent_china_keyword_hits integer,
    sample_url text,
    discovered_keyword text,
    source_query text,
    discovered_at text,
    last_checked_at text,
    imported_at timestamptz not null default now(),
    unique (ats_type, ats_token)
);

create index if not exists china_jobs_company_idx
    on public.china_jobs (company_name);

create index if not exists china_jobs_ats_type_idx
    on public.china_jobs (ats_type);

create index if not exists china_jobs_recency_idx
    on public.china_jobs (recency_status);

create index if not exists china_jobs_last_seen_idx
    on public.china_jobs (last_seen_at desc);

create index if not exists china_jobs_age_idx
    on public.china_jobs (ats_age_days);

create index if not exists china_jobs_remote_idx
    on public.china_jobs (is_remote);

create index if not exists china_companies_hits_idx
    on public.china_companies (china_keyword_hits desc);
